---
name: openapi-validate
on:
  push:
  workflow_dispatch:
jobs:
  check-openapi-definition:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    name: Swagger Editor Validator Remote
    steps:
      - name: 📄 Checkout the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          fetch-depth: 1
          persist-credentials: false  # Do not persist credentials for security
      - name: 🧪 Validate OpenAPI definition
        uses: swaggerexpert/swagger-editor-validate@264fd875d3c6e1bf65da1f0a63e095cbe41ffef3  # v1.5.1
        with:
          definition-file: docs/openapi.json
